# Generated by Django 2.2.24 on 2022-07-31 13:23

from django.db import migrations


def set_owner_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        flats_set = Flat.objects.filter(
            owner=owner.full_name,
            owners_phonenumber=owner.owners_phonenumber
        )
        owner.flats.set(flats_set)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220731_1621'),
    ]

    operations = [
        migrations.RunPython(set_owner_flats),
    ]
